# unbind
$ ignore
9 ignore
A ignore
ctrl+c ignore
ctrl++ ignore
ctrl+- ignore
ctrl+v ignore
ctrl+w ignore
ctrl+z ignore
d ignore
e ignore
E ignore
F ignore
! ignore
% ignore
& ignore
( ignore
) ignore
* ignore
+ ignore
, ignore
. ignore
@ ignore
^ ignore
_ ignore
i ignore
J ignore
o ignore
r ignore
R ignore
SHARP ignore
s ignore
t ignore
T ignore
u ignore
V ignore
w ignore
W ignore
y ignore
z ignore
Z ignore

# bind
h seek -1
l seek 1

f seek 10
b seek -10

g-g seek 0 absolute-percent
G seek 100 absolute-percent

ctrl+n frame-step
ctrl+p frame-back-step

p playlist-prev; show-text ${playlist}
n playlist-next; show-text ${playlist}

L cycle-values loop-file "inf" "no"

c add chapter 1
C add chapter -1

[ multiply speed 1/1.1
] multiply speed 1.1
\ set speed 1.0

BS cycle mute
- add volume -2
= add volume 2

| vf toggle hflip
_ vf toggle vflip
> cycle_values video-rotate "90" "180" "270" "0"
< cycle_values video-rotate  "270" "180" "90" "0"

i add video-zoom 0.1
o add video-zoom -0.1

h add video-pan-x 0.1
j add video-pan-y -0.1
k add video-pan-y 0.1
l add video-pan-x -0.1

z set video-zoom 0 ; set video-pan-x 0; set video-pan-y 0

S screenshot video

v cycle sub-visibility

ctrl+k add sub-pos -5
ctrl+j add sub-pos +5

ctrl+h add sub-delay -0.1
ctrl+l add sub-delay 0.1

ctrl+i add sub-scale 0.1
ctrl+o add sub-scale -0.1
