# Unbind
ctrl+w      ignore
ctrl+c      ignore

# Bind
h seek -1
l seek 1

f seek 10
b seek -10

g-g seek 0 absolute-percent
G seek 100 absolute-percent

ctrl+n frame-step
ctrl+p frame-back-step

p playlist-prev; show-text ${playlist}
n playlist-next; show-text ${playlist}

L cycle-values loop-file "inf" "no"

c add chapter 1
C add chapter -1

[ multiply speed 1/1.1
] multiply speed 1.1
\ set speed 1.0

BS cycle mute
- add volume -2
= add volume 2

| vf toggle vflip
_ vf toggle hflip
> cycle_values video-rotate "90" "180" "270" "0"
< cycle_values video-rotate  "270" "180" "90" "0"

Ctrl+i add video-zoom 0.1
Ctrl+o add video-zoom -0.1

Ctrl+h add video-pan-x 0.1
Ctrl+j add video-pan-y -0.1
Ctrl+k add video-pan-y 0.1
Ctrl+l add video-pan-x -0.1

z set video-zoom 0 ; set video-pan-x 0; set video-pan-y 0


S screenshot video

k add sub-pos -5
j add sub-pos +5

, add sub-delay -0.1
. add sub-delay 0.1

s-s cycle sub-visibility

s-i add sub-scale 0.1
s-o add sub-scale -0.1
s-z set sub-scale 1.0

# Default
o show-progress
O no-osd cycle-values osd-level 3 1
i script-binding stats/display-stats
I script-binding stats/display-stats-toggle
g-b script-binding select/select-binding
g-c script-binding select/select-chapter
g-p script-binding select/select-playlist
g-l script-binding select/select-subtitle-line
g-m script-binding select/menu
