syntax on

set number
set relativenumber

set expandtab
set tabstop=4
set shiftwidth=4
set smartindent

set ignorecase
set smartcase

set hlsearch
set incsearch

set background=dark
if index(['linux', 'dvtm-256color'], $TERM) == -1
    set termguicolors
endif

set laststatus=2

set viminfofile=~/.cache/vim/viminfo

set clipboard=unnamedplus

source ${HOME}/.config/vim/autocmds.vim
