[Metadata]
Name=mono

[InputPanel]
EnableBlur=False
NormalColor=#eeeeee
HighlightCandidateColor=#111111
HighlightColor=#111111
HighlightBackgroundColor=#111111
Spacing=0

[InputPanel/Highlight]
Color=#aaaaaa

[InputPanel/Background]
Color=#111111

[InputPanel/ContentMargin]
Left=6
Right=6
Top=0
Bottom=0

[InputPanel/TextMargin]
Left=6
Right=6
Top=0
Bottom=0

[InputPanel/Background/Margin]
Left=6
Right=6
Top=0
Bottom=0

[InputPanel/Highlight/Margin]
Left=6
Right=6
Top=0
Bottom=0

[InputPanel/PrevPage/ClickMargin]
Left=0
Right=0
Top=0
Bottom=0

[InputPanel/NextPage/ClickMargin]
Left=0
Right=0
Top=0
Bottom=0
