#!/bin/sh

delete() {
    choice="$(printf "no\nyes" | dmenu -p "rm?")" &&
        [ "$choice" = "yes" ] && rm "$file"
}

show_exif() {
    st -t _floating_ sh -c "exiftool \"$file\"  | less -R"
}

rename_img() {
    new_name="$(dmenu -p "rename: ")"
    dir_name="${file%/*}"
    [ -n "$new_name" ] && mv "$file" "$dir_name/$new_name"

}

scan_qrcode() {
    qrtool decode "$file" | xsel -b &&
        notify-send "nsxiv" "Copied to clipboard"
}

while read file; do
    case "$1" in
        "d") delete ;;
        "e") show_exif ;;
        "r") rename_img ;;
        "s") scan_qrcode ;;
    esac
done
