c.colors.completion.category.bg = '#aaaaaa'
c.colors.completion.category.fg = '#000000'
c.colors.completion.even.bg = '#000000'
c.colors.completion.item.selected.bg = '#aaaaaa'
c.colors.completion.item.selected.border.bottom = '#000000'
c.colors.completion.item.selected.border.top = '#000000'
c.colors.completion.item.selected.fg = '#000000'
c.colors.completion.item.selected.match.fg = '#55ff55'
c.colors.completion.match.fg = '#00aa00'
c.colors.completion.odd.bg = '#000000'

c.colors.downloads.bar.bg = '#000000'

c.colors.hints.bg = '#000000'
c.colors.hints.fg = '#ffffff'
c.colors.hints.match.fg = '#000000'

c.colors.messages.error.border = '#000000'
c.colors.messages.info.border = '#000000'
c.colors.messages.warning.border = '#000000'

c.colors.prompts.bg = '#000000'
c.colors.prompts.border = '2px solid #aaaaaa'
c.colors.prompts.fg = '#ffffff'

c.colors.statusbar.caret.bg = '#000000'
c.colors.statusbar.caret.fg = '#ffffff'
c.colors.statusbar.caret.selection.bg = '#000000'
c.colors.statusbar.caret.selection.fg = '#ffffff'
c.colors.statusbar.command.bg = '#000000'
c.colors.statusbar.command.fg = '#ffffff'
c.colors.statusbar.insert.bg = '#000000'
c.colors.statusbar.insert.fg = '#ffffff'
c.colors.statusbar.normal.bg = '#aaaaaa'
c.colors.statusbar.normal.fg = '#000000'
c.colors.statusbar.passthrough.bg = '#000000'
c.colors.statusbar.passthrough.fg = '#ffffff'
c.colors.statusbar.url.error.fg = '#000000'
c.colors.statusbar.url.fg = '#000000'
c.colors.statusbar.url.hover.fg = '#000000'
c.colors.statusbar.url.success.http.fg = '#000000'
c.colors.statusbar.url.success.https.fg = '#000000'
c.colors.statusbar.url.warn.fg = '#aa0000'

c.colors.tabs.bar.bg = '#000000'
c.colors.tabs.even.bg = '#000000'
c.colors.tabs.odd.bg = '#000000'
c.colors.tabs.pinned.even.bg = '#000000'
c.colors.tabs.pinned.even.fg = '#ffffff'
c.colors.tabs.pinned.odd.bg = '#000000'
c.colors.tabs.pinned.odd.fg = '#ffffff'
c.colors.tabs.pinned.selected.even.bg = '#aaaaaa'
c.colors.tabs.pinned.selected.even.fg = '#000000'
c.colors.tabs.pinned.selected.odd.bg = '#aaaaaa'
c.colors.tabs.pinned.selected.odd.fg = '#000000'
c.colors.tabs.selected.even.bg = '#aaaaaa'
c.colors.tabs.selected.even.fg = '#000000'
c.colors.tabs.selected.odd.bg = '#aaaaaa'
c.colors.tabs.selected.odd.fg = '#000000'

c.colors.webpage.bg = '#000000' # Fix flash in darkmode
c.colors.webpage.darkmode.enabled = True
c.colors.webpage.darkmode.policy.images = 'never'

c.hints.border = '2px solid #aaaaaa'
