music_directory     "$HOME/mus"
playlist_directory  "$HOME/mus/.playlists"
db_file             "$XDG_CACHE_HOME/mpd/database"
log_file            "$XDG_CACHE_HOME/mpd/log"
sticker_file        "$XDG_CACHE_HOME/mpd/sticker.sql"
pid_file            "$XDG_RUNTIME_DIR/mpd/mpd.pid"
state_file          "$XDG_RUNTIME_DIR/mpd/state"

bind_to_address     "$XDG_RUNTIME_DIR/mpd/socket"

auto_update "yes"

audio_output {
    type            "pipewire"
    name            "PipeWire output"
}
