#!/bin/sh
# Search the currently selected word with dictd

tmp=${XDG_RUNTIME_DIR}/qutebrowser/qutedict

terminal="st -c _floating_ -t Userscripts/dict"

dict $QUTE_SELECTED_TEXT > "$tmp" 2>&1

$terminal less "$tmp"
